name: extend_material
description: A Flutter package that extends the existing material package, to support Material3 content such as M3 motion/transition, components, and ...
version: 0.0.1
repository: https://github.com/Hamion/extend_material
issue_tracker: https://github.com/Hamion/extend_material/issues
platforms:
  # android:
  # ios:
  # linux:
  # macos:
  web:
#   # windows:
# screenshots:
#   - description: 'This screenshot shows the thumbnail of the package'
#     path: assets/Material design 3 side sheet.jpg

environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.2
  # test: ^1.21.0
dependencies:
  flutter:
    sdk: flutter
